version: '3.8'

services:
  habits-frontend-dev:
    build:
      context: .
      target: builder  # Stop at builder stage for development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_APP_NAME=Habits Adventure
      - VITE_ENABLE_DICE=true
      - VITE_DEBUG_MODE=true
    command: npm run dev
    restart: unless-stopped
    networks:
      - habits-dev-network

  # Development database
  neptune-dev:
    image: tinkerpop/gremlin-server:latest
    ports:
      - "8182:8182"
    volumes:
      - neptune-dev-data:/opt/gremlin-server/data
    restart: unless-stopped
    networks:
      - habits-dev-network

networks:
  habits-dev-network:
    driver: bridge

volumes:
  neptune-dev-data:
    driver: local